/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    blog: Blog;
    categories: Category;
    'store-config': StoreConfig;
    navigation: Navigation;
    'content-blocks': ContentBlock;
    'legal-pages': LegalPage;
    'product-collections': ProductCollection;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    blog: BlogSelect<false> | BlogSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'store-config': StoreConfigSelect<false> | StoreConfigSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    'content-blocks': ContentBlocksSelect<false> | ContentBlocksSelect<true>;
    'legal-pages': LegalPagesSelect<false> | LegalPagesSelect<true>;
    'product-collections': ProductCollectionsSelect<false> | ProductCollectionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * User role for access control
   */
  role: 'admin' | 'editor' | 'user';
  inviteToken?: string | null;
  inviteTokenExpiry?: string | null;
  /**
   * Status of user invitation
   */
  inviteStatus?: ('pending' | 'accepted') | null;
  /**
   * User who sent the invitation
   */
  invitedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alternative text for accessibility and SEO
   */
  alt?: string | null;
  /**
   * Caption or description for the media
   */
  caption?: string | null;
  /**
   * Type of media file
   */
  mediaType?: ('image' | 'video' | 'audio' | 'document' | 'archive' | 'other') | null;
  /**
   * How this media is used
   */
  usage?:
    | (
        | 'product'
        | 'category'
        | 'hero'
        | 'branding'
        | 'icon'
        | 'background'
        | 'content'
        | 'social'
        | 'marketing'
        | 'legal'
        | 'other'
      )[]
    | null;
  /**
   * Tags for organizing media files
   */
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * SEO metadata for this media
   */
  seo?: {
    /**
     * SEO title for the image
     */
    title?: string | null;
    /**
     * SEO description
     */
    description?: string | null;
    /**
     * Comma-separated keywords
     */
    keywords?: string | null;
  };
  /**
   * Image optimization status
   */
  optimization?: {
    /**
     * Has this image been optimized?
     */
    optimized?: boolean | null;
    /**
     * Compression level applied
     */
    compressionLevel?: ('none' | 'low' | 'medium' | 'high') | null;
    /**
     * WebP version generated
     */
    webpGenerated?: boolean | null;
    /**
     * AVIF version generated
     */
    avifGenerated?: boolean | null;
  };
  /**
   * Image dimensions
   */
  dimensions?: {
    /**
     * Image width in pixels
     */
    width?: number | null;
    /**
     * Image height in pixels
     */
    height?: number | null;
    /**
     * Calculated aspect ratio
     */
    aspectRatio?: string | null;
  };
  /**
   * Accessibility information
   */
  accessibility?: {
    /**
     * Check if this image is purely decorative (hides from screen readers)
     */
    isDecorative?: boolean | null;
    /**
     * Detailed description for complex images
     */
    longDescription?: string | null;
    /**
     * Text transcription for images containing text
     */
    transcription?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  /**
   * Copyright and licensing information
   */
  copyright?: {
    /**
     * Copyright owner
     */
    owner?: string | null;
    /**
     * License type
     */
    license?: ('all-rights' | 'cc' | 'public' | 'royalty-free' | 'licensed' | 'stock') | null;
    /**
     * Required attribution text
     */
    attribution?: string | null;
    /**
     * Source URL or reference
     */
    source?: string | null;
  };
  status?: ('active' | 'archived' | 'review' | 'needs-optimization') | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    desktop?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  pageType?: ('landing' | 'content' | 'product' | 'category' | 'marketing' | 'blog') | null;
  /**
   * Short description for SEO and previews
   */
  excerpt?: string | null;
  /**
   * Flexible content blocks for page layout
   */
  contentBlocks?:
    | (
        | {
            /**
             * Main hero title
             */
            title: string;
            /**
             * Hero subtitle
             */
            subtitle?: string | null;
            /**
             * Hero description text
             */
            description?: string | null;
            /**
             * Hero background image
             */
            backgroundImage?: (number | null) | Media;
            ctaText?: string | null;
            ctaLink?: string | null;
            ctaType?: ('primary' | 'secondary' | 'outline') | null;
            alignment?: ('left' | 'center' | 'right') | null;
            textColor?: ('dark' | 'light') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            alignment?: ('left' | 'center' | 'right') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textBlock';
          }
        | {
            title?: string | null;
            description?: string | null;
            images?:
              | {
                  image: number | Media;
                  caption?: string | null;
                  alt: string;
                  id?: string | null;
                }[]
              | null;
            layout?: ('grid' | 'carousel' | 'masonry') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageGallery';
          }
        | {
            testimonials?:
              | {
                  quote: string;
                  author: string;
                  title?: string | null;
                  company?: string | null;
                  avatar?: (number | null) | Media;
                  rating?: number | null;
                  id?: string | null;
                }[]
              | null;
            layout?: ('cards' | 'carousel' | 'list') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            title?: string | null;
            description?: string | null;
            features?:
              | {
                  title: string;
                  description?: string | null;
                  icon?: (number | null) | Media;
                  link?: string | null;
                  id?: string | null;
                }[]
              | null;
            layout?: ('grid' | 'list' | 'cards') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'features';
          }
        | {
            title: string;
            description?: string | null;
            buttonText: string;
            buttonLink: string;
            buttonStyle?: ('primary' | 'secondary' | 'outline') | null;
            backgroundColor?: string | null;
            backgroundImage?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            title?: string | null;
            description?: string | null;
            /**
             * Select a product collection from your store
             */
            collection: number | ProductCollection;
            /**
             * Number of products to display
             */
            limit?: number | null;
            layout?: ('grid' | 'carousel' | 'list') | null;
            showPrice?: boolean | null;
            showAddToCart?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'productCollectionBlock';
          }
        | {
            title?: string | null;
            description?: string | null;
            videoType: 'youtube' | 'vimeo' | 'upload' | 'embed';
            /**
             * YouTube video ID (e.g., dQw4w9WgXcQ from https://youtube.com/watch?v=dQw4w9WgXcQ)
             */
            youtubeId?: string | null;
            /**
             * Vimeo video ID
             */
            vimeoId?: string | null;
            /**
             * Upload a video file
             */
            videoFile?: (number | null) | Media;
            /**
             * Paste your custom embed/iframe code
             */
            embedCode?: string | null;
            /**
             * Video thumbnail image (optional)
             */
            thumbnail?: (number | null) | Media;
            /**
             * Auto-play video on page load
             */
            autoplay?: boolean | null;
            /**
             * Show video controls
             */
            controls?: boolean | null;
            aspectRatio?: ('ratio_16_9' | 'ratio_4_3' | 'ratio_1_1') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'video';
          }
        | {
            /**
             * Section title
             */
            title?: string | null;
            /**
             * Optional section description
             */
            description?: string | null;
            /**
             * Select blog posts to display
             */
            posts: (number | Blog)[];
            /**
             * Maximum number of posts to display
             */
            limit?: number | null;
            /**
             * How to display the blog posts
             */
            layout?: ('grid' | 'list' | 'carousel' | 'featured-grid') | null;
            /**
             * Show post excerpt/summary
             */
            showExcerpt?: boolean | null;
            /**
             * Show post author
             */
            showAuthor?: boolean | null;
            /**
             * Show published date
             */
            showDate?: boolean | null;
            /**
             * Show post category
             */
            showCategory?: boolean | null;
            /**
             * Show "Read More" button
             */
            showReadMore?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'blogPosts';
          }
        | {
            /**
             * Select a reusable block from the Content Blocks library
             */
            blockReference: number | ContentBlock;
            id?: string | null;
            blockName?: string | null;
            blockType: 'reusableContentBlock';
          }
      )[]
    | null;
  featuredImage?: (number | null) | Media;
  seo?: {
    /**
     * SEO title (leave empty to use page title)
     */
    title?: string | null;
    /**
     * SEO meta description
     */
    description?: string | null;
    /**
     * Comma-separated keywords
     */
    keywords?: string | null;
    /**
     * Open Graph image for social sharing
     */
    ogImage?: (number | null) | Media;
    /**
     * Open Graph title (leave empty to use SEO title)
     */
    ogTitle?: string | null;
    /**
     * Open Graph description
     */
    ogDescription?: string | null;
    /**
     * Canonical URL for this page
     */
    canonicalUrl?: string | null;
    /**
     * Prevent search engines from indexing this page
     */
    noIndex?: boolean | null;
  };
  /**
   * When this page was first published
   */
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Auto-synced from backend - do not edit manually
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-collections".
 */
export interface ProductCollection {
  id: number;
  collectionId: string;
  title: string;
  handle?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog".
 */
export interface Blog {
  id: number;
  title: string;
  slug: string;
  author?: (number | null) | User;
  /**
   * Short summary for previews and SEO
   */
  excerpt: string;
  contentBlocks: (
    | {
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        alignment?: ('left' | 'center' | 'right') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'textBlock';
      }
    | {
        title?: string | null;
        description?: string | null;
        images?:
          | {
              image: number | Media;
              caption?: string | null;
              alt: string;
              id?: string | null;
            }[]
          | null;
        layout?: ('grid' | 'carousel' | 'masonry') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'imageGallery';
      }
    | {
        title?: string | null;
        description?: string | null;
        videoType: 'youtube' | 'vimeo' | 'upload' | 'embed';
        /**
         * YouTube video ID (e.g., dQw4w9WgXcQ from https://youtube.com/watch?v=dQw4w9WgXcQ)
         */
        youtubeId?: string | null;
        /**
         * Vimeo video ID
         */
        vimeoId?: string | null;
        /**
         * Upload a video file
         */
        videoFile?: (number | null) | Media;
        /**
         * Paste your custom embed/iframe code
         */
        embedCode?: string | null;
        /**
         * Video thumbnail image (optional)
         */
        thumbnail?: (number | null) | Media;
        /**
         * Auto-play video on page load
         */
        autoplay?: boolean | null;
        /**
         * Show video controls
         */
        controls?: boolean | null;
        aspectRatio?: ('ratio_16_9' | 'ratio_4_3' | 'ratio_1_1') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'video';
      }
    | {
        title: string;
        description?: string | null;
        buttonText: string;
        buttonLink: string;
        buttonStyle?: ('primary' | 'secondary' | 'outline') | null;
        backgroundColor?: string | null;
        backgroundImage?: (number | null) | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'cta';
      }
    | {
        title?: string | null;
        description?: string | null;
        /**
         * Select a product collection from your store
         */
        collection: number | ProductCollection;
        /**
         * Number of products to display
         */
        limit?: number | null;
        layout?: ('grid' | 'carousel' | 'list') | null;
        showPrice?: boolean | null;
        showAddToCart?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'productCollectionBlock';
      }
    | {
        /**
         * Select a reusable block from the Content Blocks library
         */
        blockReference: number | ContentBlock;
        id?: string | null;
        blockName?: string | null;
        blockType: 'reusableContentBlock';
      }
  )[];
  featuredImage: number | Media;
  categories?: (number | Category)[] | null;
  /**
   * Tags for organizing and filtering blog posts
   */
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Estimated read time in minutes
   */
  readTime?: number | null;
  /**
   * Related blog posts to show at the end
   */
  relatedPosts?: (number | Blog)[] | null;
  seo?: {
    /**
     * SEO title (leave empty to use post title)
     */
    title?: string | null;
    /**
     * SEO meta description
     */
    description?: string | null;
    /**
     * Comma-separated keywords
     */
    keywords?: string | null;
    /**
     * Open Graph image for social sharing
     */
    ogImage?: (number | null) | Media;
    /**
     * Prevent search engines from indexing this post
     */
    noIndex?: boolean | null;
  };
  /**
   * When this post was published
   */
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-blocks".
 */
export interface ContentBlock {
  id: number;
  /**
   * Internal name for this content block
   */
  name: string;
  /**
   * Select the block to reuse
   */
  content?:
    | (
        | {
            /**
             * Main hero title
             */
            title: string;
            /**
             * Hero subtitle
             */
            subtitle?: string | null;
            /**
             * Hero description text
             */
            description?: string | null;
            /**
             * Hero background image
             */
            backgroundImage?: (number | null) | Media;
            ctaText?: string | null;
            ctaLink?: string | null;
            ctaType?: ('primary' | 'secondary' | 'outline') | null;
            alignment?: ('left' | 'center' | 'right') | null;
            textColor?: ('dark' | 'light') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            title?: string | null;
            description?: string | null;
            features?:
              | {
                  title: string;
                  description?: string | null;
                  icon?: (number | null) | Media;
                  link?: string | null;
                  id?: string | null;
                }[]
              | null;
            layout?: ('grid' | 'list' | 'cards') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'features';
          }
        | {
            testimonials?:
              | {
                  quote: string;
                  author: string;
                  title?: string | null;
                  company?: string | null;
                  avatar?: (number | null) | Media;
                  rating?: number | null;
                  id?: string | null;
                }[]
              | null;
            layout?: ('cards' | 'carousel' | 'list') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            title: string;
            description?: string | null;
            buttonText: string;
            buttonLink: string;
            buttonStyle?: ('primary' | 'secondary' | 'outline') | null;
            backgroundColor?: string | null;
            backgroundImage?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            title?: string | null;
            description?: string | null;
            images?:
              | {
                  image: number | Media;
                  caption?: string | null;
                  alt: string;
                  id?: string | null;
                }[]
              | null;
            layout?: ('grid' | 'carousel' | 'masonry') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageGallery';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            alignment?: ('left' | 'center' | 'right') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textBlock';
          }
        | {
            title?: string | null;
            description?: string | null;
            videoType: 'youtube' | 'vimeo' | 'upload' | 'embed';
            /**
             * YouTube video ID (e.g., dQw4w9WgXcQ from https://youtube.com/watch?v=dQw4w9WgXcQ)
             */
            youtubeId?: string | null;
            /**
             * Vimeo video ID
             */
            vimeoId?: string | null;
            /**
             * Upload a video file
             */
            videoFile?: (number | null) | Media;
            /**
             * Paste your custom embed/iframe code
             */
            embedCode?: string | null;
            /**
             * Video thumbnail image (optional)
             */
            thumbnail?: (number | null) | Media;
            /**
             * Auto-play video on page load
             */
            autoplay?: boolean | null;
            /**
             * Show video controls
             */
            controls?: boolean | null;
            aspectRatio?: ('ratio_16_9' | 'ratio_4_3' | 'ratio_1_1') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'video';
          }
        | {
            title?: string | null;
            description?: string | null;
            faqs?:
              | {
                  question: string;
                  answer: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  };
                  category?: string | null;
                  id?: string | null;
                }[]
              | null;
            layout?: ('accordion' | 'tabs' | 'cards') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            title?: string | null;
            description?: string | null;
            /**
             * Select a product collection from your store
             */
            collection: number | ProductCollection;
            /**
             * Number of products to display
             */
            limit?: number | null;
            layout?: ('grid' | 'carousel' | 'list') | null;
            showPrice?: boolean | null;
            showAddToCart?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'productCollectionBlock';
          }
        | {
            title: string;
            description?: string | null;
            placeholder?: string | null;
            buttonText?: string | null;
            successMessage?: string | null;
            backgroundColor?: string | null;
            backgroundImage?: (number | null) | Media;
            layout?: ('inline' | 'stacked' | 'card') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'newsletter';
          }
        | {
            title?: string | null;
            description?: string | null;
            stats?:
              | {
                  number: string;
                  label: string;
                  description?: string | null;
                  icon?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            layout?: ('cols-2' | 'cols-3' | 'cols-4') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats';
          }
      )[]
    | null;
  status?: ('active' | 'inactive' | 'draft') | null;
  /**
   * Tags for organizing content blocks
   */
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug: string;
  /**
   * Rich text description for category pages
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Brief description for category cards and previews
   */
  shortDescription?: string | null;
  parent?: (number | null) | Category;
  images?: {
    /**
     * Main category image
     */
    featuredImage?: (number | null) | Media;
    /**
     * Banner image for category pages
     */
    bannerImage?: (number | null) | Media;
    /**
     * Small icon for navigation and cards
     */
    iconImage?: (number | null) | Media;
    /**
     * Additional images for category showcase
     */
    gallery?:
      | {
          image: number | Media;
          caption?: string | null;
          alt: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Marketing and promotional content
   */
  marketing?: {
    /**
     * Marketing tagline for the category
     */
    tagline?: string | null;
    /**
     * Key features or benefits of this category
     */
    features?:
      | {
          title: string;
          description?: string | null;
          icon?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
    /**
     * Promotional banner for category pages
     */
    promotionalBanner?: {
      title?: string | null;
      description?: string | null;
      buttonText?: string | null;
      buttonLink?: string | null;
      backgroundColor?: string | null;
      backgroundImage?: (number | null) | Media;
    };
    /**
     * Related or complementary categories
     */
    relatedCategories?: (number | Category)[] | null;
  };
  /**
   * Additional content blocks for category pages
   */
  contentBlocks?:
    | (
        | {
            /**
             * Main hero title
             */
            title: string;
            /**
             * Hero subtitle
             */
            subtitle?: string | null;
            /**
             * Hero description text
             */
            description?: string | null;
            /**
             * Hero background image
             */
            backgroundImage?: (number | null) | Media;
            ctaText?: string | null;
            ctaLink?: string | null;
            ctaType?: ('primary' | 'secondary' | 'outline') | null;
            alignment?: ('left' | 'center' | 'right') | null;
            textColor?: ('dark' | 'light') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            alignment?: ('left' | 'center' | 'right') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textBlock';
          }
        | {
            title?: string | null;
            description?: string | null;
            images?:
              | {
                  image: number | Media;
                  caption?: string | null;
                  alt: string;
                  id?: string | null;
                }[]
              | null;
            layout?: ('grid' | 'carousel' | 'masonry') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageGallery';
          }
        | {
            title?: string | null;
            description?: string | null;
            videoType: 'youtube' | 'vimeo' | 'upload' | 'embed';
            /**
             * YouTube video ID (e.g., dQw4w9WgXcQ from https://youtube.com/watch?v=dQw4w9WgXcQ)
             */
            youtubeId?: string | null;
            /**
             * Vimeo video ID
             */
            vimeoId?: string | null;
            /**
             * Upload a video file
             */
            videoFile?: (number | null) | Media;
            /**
             * Paste your custom embed/iframe code
             */
            embedCode?: string | null;
            /**
             * Video thumbnail image (optional)
             */
            thumbnail?: (number | null) | Media;
            /**
             * Auto-play video on page load
             */
            autoplay?: boolean | null;
            /**
             * Show video controls
             */
            controls?: boolean | null;
            aspectRatio?: ('ratio_16_9' | 'ratio_4_3' | 'ratio_1_1') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'video';
          }
        | {
            title: string;
            description?: string | null;
            buttonText: string;
            buttonLink: string;
            buttonStyle?: ('primary' | 'secondary' | 'outline') | null;
            backgroundColor?: string | null;
            backgroundImage?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            title?: string | null;
            description?: string | null;
            /**
             * Select a product collection from your store
             */
            collection: number | ProductCollection;
            /**
             * Number of products to display
             */
            limit?: number | null;
            layout?: ('grid' | 'carousel' | 'list') | null;
            showPrice?: boolean | null;
            showAddToCart?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'productCollectionBlock';
          }
        | {
            title?: string | null;
            description?: string | null;
            features?:
              | {
                  title: string;
                  description?: string | null;
                  icon?: (number | null) | Media;
                  link?: string | null;
                  id?: string | null;
                }[]
              | null;
            layout?: ('grid' | 'list' | 'cards') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'features';
          }
        | {
            /**
             * Section title
             */
            title?: string | null;
            /**
             * Optional section description
             */
            description?: string | null;
            /**
             * Select blog posts to display
             */
            posts: (number | Blog)[];
            /**
             * Maximum number of posts to display
             */
            limit?: number | null;
            /**
             * How to display the blog posts
             */
            layout?: ('grid' | 'list' | 'carousel' | 'featured-grid') | null;
            /**
             * Show post excerpt/summary
             */
            showExcerpt?: boolean | null;
            /**
             * Show post author
             */
            showAuthor?: boolean | null;
            /**
             * Show published date
             */
            showDate?: boolean | null;
            /**
             * Show post category
             */
            showCategory?: boolean | null;
            /**
             * Show "Read More" button
             */
            showReadMore?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'blogPosts';
          }
        | {
            /**
             * Select a reusable block from the Content Blocks library
             */
            blockReference: number | ContentBlock;
            id?: string | null;
            blockName?: string | null;
            blockType: 'reusableContentBlock';
          }
      )[]
    | null;
  /**
   * Product filtering and sorting configuration
   */
  filters?: {
    /**
     * Configure available filters for this category
     */
    availableFilters?:
      | {
          filterType?: ('price' | 'brand' | 'color' | 'size' | 'material' | 'rating' | 'custom') | null;
          label: string;
          options?:
            | {
                label: string;
                value: string;
                id?: string | null;
              }[]
            | null;
          enabled?: boolean | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Default sorting for products in this category
     */
    defaultSort?:
      | (
          | 'created_at_desc'
          | 'created_at_asc'
          | 'price_asc'
          | 'price_desc'
          | 'title_asc'
          | 'title_desc'
          | 'sales_desc'
          | 'rating_desc'
        )
      | null;
  };
  status?: ('active' | 'inactive' | 'coming_soon' | 'archived') | null;
  /**
   * Category visibility settings
   */
  visibility?: {
    /**
     * Show this category in main navigation
     */
    showInNavigation?: boolean | null;
    /**
     * Show this category in footer navigation
     */
    showInFooter?: boolean | null;
    /**
     * Feature this category on homepage
     */
    featured?: boolean | null;
    /**
     * Require user authentication to view
     */
    requiresAuth?: boolean | null;
  };
  seo?: {
    /**
     * SEO title (leave empty to use category name)
     */
    title?: string | null;
    /**
     * SEO meta description
     */
    description?: string | null;
    /**
     * Comma-separated keywords
     */
    keywords?: string | null;
    /**
     * Open Graph image for social sharing
     */
    ogImage?: (number | null) | Media;
    /**
     * Canonical URL for this category
     */
    canonicalUrl?: string | null;
    /**
     * Prevent search engines from indexing
     */
    noIndex?: boolean | null;
  };
  /**
   * Used for ordering categories (lower numbers first)
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "store-config".
 */
export interface StoreConfig {
  id: number;
  /**
   * Display name of the store
   */
  storeName: string;
  /**
   * Brief description of the store
   */
  storeDescription?: string | null;
  /**
   * Store domain (e.g., mystore.com)
   */
  domain: string;
  status?: ('active' | 'maintenance' | 'inactive') | null;
  /**
   * Business contact information
   */
  businessInfo: {
    companyName: string;
    email: string;
    phone?: string | null;
    address?: {
      street?: string | null;
      city?: string | null;
      state?: string | null;
      zipCode?: string | null;
      country?: string | null;
    };
    businessHours?:
      | {
          day?: ('monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday') | null;
          openTime?: string | null;
          closeTime?: string | null;
          closed?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Visual branding elements
   */
  branding?: {
    /**
     * Main store logo
     */
    logo?: (number | null) | Media;
    /**
     * Alternative logo (light/dark mode)
     */
    logoAlt?: (number | null) | Media;
    /**
     * Favicon (16x16 or 32x32 px)
     */
    favicon?: (number | null) | Media;
    /**
     * Primary brand color (hex code)
     */
    primaryColor?: string | null;
    /**
     * Secondary brand color (hex code)
     */
    secondaryColor?: string | null;
    /**
     * Accent color for CTAs (hex code)
     */
    accentColor?: string | null;
    fontFamily?: ('Inter' | 'Roboto' | 'Open Sans' | 'Lato' | 'Montserrat' | 'Poppins') | null;
  };
  /**
   * Social media profiles
   */
  socialMedia?: {
    facebook?: string | null;
    instagram?: string | null;
    twitter?: string | null;
    linkedin?: string | null;
    youtube?: string | null;
    tiktok?: string | null;
  };
  /**
   * Store policies and legal information
   */
  policies?: {
    /**
     * Link to shipping policy page
     */
    shippingPolicy?: (number | null) | LegalPage;
    /**
     * Link to return policy page
     */
    returnPolicy?: (number | null) | LegalPage;
    /**
     * Link to privacy policy page
     */
    privacyPolicy?: (number | null) | LegalPage;
    /**
     * Link to terms of service page
     */
    termsOfService?: (number | null) | LegalPage;
  };
  /**
   * Default SEO settings
   */
  seoDefaults?: {
    /**
     * Default meta title for pages
     */
    metaTitle?: string | null;
    /**
     * Default meta description
     */
    metaDescription?: string | null;
    /**
     * Default keywords (comma-separated)
     */
    metaKeywords?: string | null;
    /**
     * Default Open Graph image
     */
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages".
 */
export interface LegalPage {
  id: number;
  title: string;
  slug: string;
  pageType:
    | 'privacy'
    | 'terms'
    | 'cookies'
    | 'returns'
    | 'shipping'
    | 'refunds'
    | 'disclaimer'
    | 'gdpr'
    | 'ccpa'
    | 'accessibility'
    | 'dpa'
    | 'eula'
    | 'custom';
  /**
   * Legal page content (Text, FAQs, CTAs)
   */
  contentBlocks: (
    | {
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        alignment?: ('left' | 'center' | 'right') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'textBlock';
      }
    | {
        title?: string | null;
        description?: string | null;
        faqs?:
          | {
              question: string;
              answer: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              };
              category?: string | null;
              id?: string | null;
            }[]
          | null;
        layout?: ('accordion' | 'tabs' | 'cards') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'faq';
      }
    | {
        title: string;
        description?: string | null;
        buttonText: string;
        buttonLink: string;
        buttonStyle?: ('primary' | 'secondary' | 'outline') | null;
        backgroundColor?: string | null;
        backgroundImage?: (number | null) | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'cta';
      }
  )[];
  /**
   * When this policy takes effect
   */
  effectiveDate: string;
  /**
   * Last modification date
   */
  lastUpdated?: string | null;
  /**
   * Version number for tracking changes
   */
  version?: string | null;
  /**
   * Legal jurisdiction information
   */
  jurisdiction?: {
    /**
     * Primary jurisdiction for this legal document
     */
    country?: ('US' | 'CA' | 'GB' | 'EU' | 'AU' | 'DE' | 'FR' | 'NL' | 'OTHER') | null;
    /**
     * State/Province (if applicable)
     */
    state?: string | null;
    /**
     * Governing law clause
     */
    governingLaw?: string | null;
  };
  /**
   * Regulatory compliance flags
   */
  compliance?: {
    /**
     * GDPR compliant (EU)
     */
    gdprCompliant?: boolean | null;
    /**
     * CCPA compliant (California)
     */
    ccpaCompliant?: boolean | null;
    /**
     * COPPA compliant (Children's privacy)
     */
    coppaCompliant?: boolean | null;
    /**
     * PIPEDA compliant (Canada)
     */
    pipedaCompliant?: boolean | null;
    /**
     * LGPD compliant (Brazil)
     */
    lgpdCompliant?: boolean | null;
    /**
     * Additional compliance requirements
     */
    customCompliance?:
      | {
          regulation: string;
          description?: string | null;
          compliant?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Legal contact information
   */
  contactInfo?: {
    /**
     * Legal entity name
     */
    companyName?: string | null;
    /**
     * Legal address
     */
    address?: string | null;
    /**
     * Legal contact email
     */
    email?: string | null;
    /**
     * Legal contact phone
     */
    phone?: string | null;
    /**
     * Data Protection Officer email (GDPR)
     */
    dpoEmail?: string | null;
  };
  /**
   * Template configuration
   */
  templates?: {
    /**
     * Use pre-built template for this page type
     */
    useTemplate?: boolean | null;
    /**
     * Variables to replace in template (e.g., {{COMPANY_NAME}})
     */
    templateVariables?:
      | {
          variable: string;
          value: string;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * User notification settings
   */
  notifications?: {
    /**
     * Notify users when this policy is updated
     */
    notifyUsers?: boolean | null;
    notificationMethod?: ('email' | 'banner' | 'modal' | 'dashboard') | null;
    /**
     * Days before policy takes effect
     */
    gracePeriod?: number | null;
  };
  seo?: {
    /**
     * SEO title (leave empty to use page title)
     */
    title?: string | null;
    /**
     * SEO meta description
     */
    description?: string | null;
    /**
     * Prevent search engines from indexing (recommended for legal pages)
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * Internal name for this navigation menu
   */
  name: string;
  type: 'main' | 'footer' | 'mobile' | 'sidebar' | 'breadcrumb' | 'custom';
  /**
   * Navigation menu structure
   */
  menuItems?:
    | {
        link: {
          type: 'internal' | 'category' | 'external' | 'custom';
          internalPage?: (number | null) | Page;
          category?: (number | null) | Category;
          externalUrl?: string | null;
          customUrl?: string | null;
          /**
           * Text to display
           */
          label: string;
          newTab?: boolean | null;
        };
        /**
         * Optional icon for menu item
         */
        icon?: (number | null) | Media;
        /**
         * Optional description for mega menus
         */
        description?: string | null;
        /**
         * Highlight this menu item
         */
        featured?: boolean | null;
        /**
         * Sub-menu items (dropdown/mega menu)
         */
        children?:
          | {
              link: {
                type: 'internal' | 'category' | 'external' | 'custom';
                internalPage?: (number | null) | Page;
                category?: (number | null) | Category;
                externalUrl?: string | null;
                customUrl?: string | null;
                /**
                 * Text to display
                 */
                label: string;
                newTab?: boolean | null;
              };
              icon?: (number | null) | Media;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Navigation display settings
   */
  settings?: {
    /**
     * Maximum nesting depth for menu items
     */
    maxDepth?: number | null;
    /**
     * Display icons in navigation
     */
    showIcons?: boolean | null;
    /**
     * Show descriptions in mega menus
     */
    showDescriptions?: boolean | null;
    /**
     * Screen size where mobile navigation activates
     */
    mobileBreakpoint?: ('sm' | 'md' | 'lg' | 'xl') | null;
    /**
     * Animation for dropdown menus
     */
    animation?: ('none' | 'fade' | 'slideDown' | 'slideUp') | null;
  };
  status?: ('active' | 'inactive' | 'draft') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'blog';
        value: number | Blog;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'store-config';
        value: number | StoreConfig;
      } | null)
    | ({
        relationTo: 'navigation';
        value: number | Navigation;
      } | null)
    | ({
        relationTo: 'content-blocks';
        value: number | ContentBlock;
      } | null)
    | ({
        relationTo: 'legal-pages';
        value: number | LegalPage;
      } | null)
    | ({
        relationTo: 'product-collections';
        value: number | ProductCollection;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  inviteToken?: T;
  inviteTokenExpiry?: T;
  inviteStatus?: T;
  invitedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  mediaType?: T;
  usage?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
      };
  optimization?:
    | T
    | {
        optimized?: T;
        compressionLevel?: T;
        webpGenerated?: T;
        avifGenerated?: T;
      };
  dimensions?:
    | T
    | {
        width?: T;
        height?: T;
        aspectRatio?: T;
      };
  accessibility?:
    | T
    | {
        isDecorative?: T;
        longDescription?: T;
        transcription?: T;
      };
  copyright?:
    | T
    | {
        owner?: T;
        license?: T;
        attribution?: T;
        source?: T;
      };
  status?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        desktop?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  pageType?: T;
  excerpt?: T;
  contentBlocks?:
    | T
    | {
        hero?:
          | T
          | {
              title?: T;
              subtitle?: T;
              description?: T;
              backgroundImage?: T;
              ctaText?: T;
              ctaLink?: T;
              ctaType?: T;
              alignment?: T;
              textColor?: T;
              id?: T;
              blockName?: T;
            };
        textBlock?:
          | T
          | {
              content?: T;
              alignment?: T;
              id?: T;
              blockName?: T;
            };
        imageGallery?:
          | T
          | {
              title?: T;
              description?: T;
              images?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    alt?: T;
                    id?: T;
                  };
              layout?: T;
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              testimonials?:
                | T
                | {
                    quote?: T;
                    author?: T;
                    title?: T;
                    company?: T;
                    avatar?: T;
                    rating?: T;
                    id?: T;
                  };
              layout?: T;
              id?: T;
              blockName?: T;
            };
        features?:
          | T
          | {
              title?: T;
              description?: T;
              features?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    link?: T;
                    id?: T;
                  };
              layout?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              title?: T;
              description?: T;
              buttonText?: T;
              buttonLink?: T;
              buttonStyle?: T;
              backgroundColor?: T;
              backgroundImage?: T;
              id?: T;
              blockName?: T;
            };
        productCollectionBlock?:
          | T
          | {
              title?: T;
              description?: T;
              collection?: T;
              limit?: T;
              layout?: T;
              showPrice?: T;
              showAddToCart?: T;
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              title?: T;
              description?: T;
              videoType?: T;
              youtubeId?: T;
              vimeoId?: T;
              videoFile?: T;
              embedCode?: T;
              thumbnail?: T;
              autoplay?: T;
              controls?: T;
              aspectRatio?: T;
              id?: T;
              blockName?: T;
            };
        blogPosts?:
          | T
          | {
              title?: T;
              description?: T;
              posts?: T;
              limit?: T;
              layout?: T;
              showExcerpt?: T;
              showAuthor?: T;
              showDate?: T;
              showCategory?: T;
              showReadMore?: T;
              id?: T;
              blockName?: T;
            };
        reusableContentBlock?:
          | T
          | {
              blockReference?: T;
              id?: T;
              blockName?: T;
            };
      };
  featuredImage?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        ogImage?: T;
        ogTitle?: T;
        ogDescription?: T;
        canonicalUrl?: T;
        noIndex?: T;
      };
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog_select".
 */
export interface BlogSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  author?: T;
  excerpt?: T;
  contentBlocks?:
    | T
    | {
        textBlock?:
          | T
          | {
              content?: T;
              alignment?: T;
              id?: T;
              blockName?: T;
            };
        imageGallery?:
          | T
          | {
              title?: T;
              description?: T;
              images?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    alt?: T;
                    id?: T;
                  };
              layout?: T;
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              title?: T;
              description?: T;
              videoType?: T;
              youtubeId?: T;
              vimeoId?: T;
              videoFile?: T;
              embedCode?: T;
              thumbnail?: T;
              autoplay?: T;
              controls?: T;
              aspectRatio?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              title?: T;
              description?: T;
              buttonText?: T;
              buttonLink?: T;
              buttonStyle?: T;
              backgroundColor?: T;
              backgroundImage?: T;
              id?: T;
              blockName?: T;
            };
        productCollectionBlock?:
          | T
          | {
              title?: T;
              description?: T;
              collection?: T;
              limit?: T;
              layout?: T;
              showPrice?: T;
              showAddToCart?: T;
              id?: T;
              blockName?: T;
            };
        reusableContentBlock?:
          | T
          | {
              blockReference?: T;
              id?: T;
              blockName?: T;
            };
      };
  featuredImage?: T;
  categories?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  readTime?: T;
  relatedPosts?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        ogImage?: T;
        noIndex?: T;
      };
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  shortDescription?: T;
  parent?: T;
  images?:
    | T
    | {
        featuredImage?: T;
        bannerImage?: T;
        iconImage?: T;
        gallery?:
          | T
          | {
              image?: T;
              caption?: T;
              alt?: T;
              id?: T;
            };
      };
  marketing?:
    | T
    | {
        tagline?: T;
        features?:
          | T
          | {
              title?: T;
              description?: T;
              icon?: T;
              id?: T;
            };
        promotionalBanner?:
          | T
          | {
              title?: T;
              description?: T;
              buttonText?: T;
              buttonLink?: T;
              backgroundColor?: T;
              backgroundImage?: T;
            };
        relatedCategories?: T;
      };
  contentBlocks?:
    | T
    | {
        hero?:
          | T
          | {
              title?: T;
              subtitle?: T;
              description?: T;
              backgroundImage?: T;
              ctaText?: T;
              ctaLink?: T;
              ctaType?: T;
              alignment?: T;
              textColor?: T;
              id?: T;
              blockName?: T;
            };
        textBlock?:
          | T
          | {
              content?: T;
              alignment?: T;
              id?: T;
              blockName?: T;
            };
        imageGallery?:
          | T
          | {
              title?: T;
              description?: T;
              images?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    alt?: T;
                    id?: T;
                  };
              layout?: T;
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              title?: T;
              description?: T;
              videoType?: T;
              youtubeId?: T;
              vimeoId?: T;
              videoFile?: T;
              embedCode?: T;
              thumbnail?: T;
              autoplay?: T;
              controls?: T;
              aspectRatio?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              title?: T;
              description?: T;
              buttonText?: T;
              buttonLink?: T;
              buttonStyle?: T;
              backgroundColor?: T;
              backgroundImage?: T;
              id?: T;
              blockName?: T;
            };
        productCollectionBlock?:
          | T
          | {
              title?: T;
              description?: T;
              collection?: T;
              limit?: T;
              layout?: T;
              showPrice?: T;
              showAddToCart?: T;
              id?: T;
              blockName?: T;
            };
        features?:
          | T
          | {
              title?: T;
              description?: T;
              features?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    link?: T;
                    id?: T;
                  };
              layout?: T;
              id?: T;
              blockName?: T;
            };
        blogPosts?:
          | T
          | {
              title?: T;
              description?: T;
              posts?: T;
              limit?: T;
              layout?: T;
              showExcerpt?: T;
              showAuthor?: T;
              showDate?: T;
              showCategory?: T;
              showReadMore?: T;
              id?: T;
              blockName?: T;
            };
        reusableContentBlock?:
          | T
          | {
              blockReference?: T;
              id?: T;
              blockName?: T;
            };
      };
  filters?:
    | T
    | {
        availableFilters?:
          | T
          | {
              filterType?: T;
              label?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              enabled?: T;
              id?: T;
            };
        defaultSort?: T;
      };
  status?: T;
  visibility?:
    | T
    | {
        showInNavigation?: T;
        showInFooter?: T;
        featured?: T;
        requiresAuth?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
      };
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "store-config_select".
 */
export interface StoreConfigSelect<T extends boolean = true> {
  storeName?: T;
  storeDescription?: T;
  domain?: T;
  status?: T;
  businessInfo?:
    | T
    | {
        companyName?: T;
        email?: T;
        phone?: T;
        address?:
          | T
          | {
              street?: T;
              city?: T;
              state?: T;
              zipCode?: T;
              country?: T;
            };
        businessHours?:
          | T
          | {
              day?: T;
              openTime?: T;
              closeTime?: T;
              closed?: T;
              id?: T;
            };
      };
  branding?:
    | T
    | {
        logo?: T;
        logoAlt?: T;
        favicon?: T;
        primaryColor?: T;
        secondaryColor?: T;
        accentColor?: T;
        fontFamily?: T;
      };
  socialMedia?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        twitter?: T;
        linkedin?: T;
        youtube?: T;
        tiktok?: T;
      };
  policies?:
    | T
    | {
        shippingPolicy?: T;
        returnPolicy?: T;
        privacyPolicy?: T;
        termsOfService?: T;
      };
  seoDefaults?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        metaKeywords?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  menuItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              internalPage?: T;
              category?: T;
              externalUrl?: T;
              customUrl?: T;
              label?: T;
              newTab?: T;
            };
        icon?: T;
        description?: T;
        featured?: T;
        children?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    internalPage?: T;
                    category?: T;
                    externalUrl?: T;
                    customUrl?: T;
                    label?: T;
                    newTab?: T;
                  };
              icon?: T;
              id?: T;
            };
        id?: T;
      };
  settings?:
    | T
    | {
        maxDepth?: T;
        showIcons?: T;
        showDescriptions?: T;
        mobileBreakpoint?: T;
        animation?: T;
      };
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-blocks_select".
 */
export interface ContentBlocksSelect<T extends boolean = true> {
  name?: T;
  content?:
    | T
    | {
        hero?:
          | T
          | {
              title?: T;
              subtitle?: T;
              description?: T;
              backgroundImage?: T;
              ctaText?: T;
              ctaLink?: T;
              ctaType?: T;
              alignment?: T;
              textColor?: T;
              id?: T;
              blockName?: T;
            };
        features?:
          | T
          | {
              title?: T;
              description?: T;
              features?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    link?: T;
                    id?: T;
                  };
              layout?: T;
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              testimonials?:
                | T
                | {
                    quote?: T;
                    author?: T;
                    title?: T;
                    company?: T;
                    avatar?: T;
                    rating?: T;
                    id?: T;
                  };
              layout?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              title?: T;
              description?: T;
              buttonText?: T;
              buttonLink?: T;
              buttonStyle?: T;
              backgroundColor?: T;
              backgroundImage?: T;
              id?: T;
              blockName?: T;
            };
        imageGallery?:
          | T
          | {
              title?: T;
              description?: T;
              images?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    alt?: T;
                    id?: T;
                  };
              layout?: T;
              id?: T;
              blockName?: T;
            };
        textBlock?:
          | T
          | {
              content?: T;
              alignment?: T;
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              title?: T;
              description?: T;
              videoType?: T;
              youtubeId?: T;
              vimeoId?: T;
              videoFile?: T;
              embedCode?: T;
              thumbnail?: T;
              autoplay?: T;
              controls?: T;
              aspectRatio?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              title?: T;
              description?: T;
              faqs?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    category?: T;
                    id?: T;
                  };
              layout?: T;
              id?: T;
              blockName?: T;
            };
        productCollectionBlock?:
          | T
          | {
              title?: T;
              description?: T;
              collection?: T;
              limit?: T;
              layout?: T;
              showPrice?: T;
              showAddToCart?: T;
              id?: T;
              blockName?: T;
            };
        newsletter?:
          | T
          | {
              title?: T;
              description?: T;
              placeholder?: T;
              buttonText?: T;
              successMessage?: T;
              backgroundColor?: T;
              backgroundImage?: T;
              layout?: T;
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              title?: T;
              description?: T;
              stats?:
                | T
                | {
                    number?: T;
                    label?: T;
                    description?: T;
                    icon?: T;
                    id?: T;
                  };
              layout?: T;
              id?: T;
              blockName?: T;
            };
      };
  status?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages_select".
 */
export interface LegalPagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  pageType?: T;
  contentBlocks?:
    | T
    | {
        textBlock?:
          | T
          | {
              content?: T;
              alignment?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              title?: T;
              description?: T;
              faqs?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    category?: T;
                    id?: T;
                  };
              layout?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              title?: T;
              description?: T;
              buttonText?: T;
              buttonLink?: T;
              buttonStyle?: T;
              backgroundColor?: T;
              backgroundImage?: T;
              id?: T;
              blockName?: T;
            };
      };
  effectiveDate?: T;
  lastUpdated?: T;
  version?: T;
  jurisdiction?:
    | T
    | {
        country?: T;
        state?: T;
        governingLaw?: T;
      };
  compliance?:
    | T
    | {
        gdprCompliant?: T;
        ccpaCompliant?: T;
        coppaCompliant?: T;
        pipedaCompliant?: T;
        lgpdCompliant?: T;
        customCompliance?:
          | T
          | {
              regulation?: T;
              description?: T;
              compliant?: T;
              id?: T;
            };
      };
  contactInfo?:
    | T
    | {
        companyName?: T;
        address?: T;
        email?: T;
        phone?: T;
        dpoEmail?: T;
      };
  templates?:
    | T
    | {
        useTemplate?: T;
        templateVariables?:
          | T
          | {
              variable?: T;
              value?: T;
              description?: T;
              id?: T;
            };
      };
  notifications?:
    | T
    | {
        notifyUsers?: T;
        notificationMethod?: T;
        gracePeriod?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-collections_select".
 */
export interface ProductCollectionsSelect<T extends boolean = true> {
  collectionId?: T;
  title?: T;
  handle?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}

